# Use postgres/example user/password credentials
version: '3.3'
services:
  app:
    container_name: backand
    image: backand
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbmysql

  dbmysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: suprab
      MYSQL_USER: root
      MYSQL_PASSWORD: root

volumes:
  db_data: {}
